import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import QuizModal from "@/modals/QuizModal";
import PageTransitionLoader from "@/components/PageProgressLoader";
import QuestionModal from "@/modals/QuestionModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#3d3da8] hide-scrollbar`}
      >
        <div style={{ height: "100vh", overflow: "hidden" }}>
          {children}
          <Toaster />
          <PageTransitionLoader />
          <QuizModal />
          <QuestionModal />
        </div>
      </body>
    </html>
  );
}
